### ISSUE TITLE
˳ и w в словаре

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#101]
К слову ærmg˳yroj (оно принадлежит @jvsntsn) есть хреф на dong˳yroj
![image](https://user-images.githubusercontent.com/13102259/76622271-3d5d6800-6542-11ea-90cf-94ab9cbc4fb1.png)

а в самом словаре оно фигурирует как dongwyroj
![image](https://user-images.githubusercontent.com/13102259/76622170-0a1ad900-6542-11ea-9e86-c9caaf14de7d.png)

как писать?

ишью похоже на #99

**Comment by obelyaev** [comment]
Везде надо сделать кружочек (dong˳yroj). Обратите внимание на то, как цитируется слово k˳yroj: там одновременно и w, и кружок (kw˳yroj), чего быть не может. Т.е. это опечатка.

Теоретически в иронском можно представить различие цепочек "kwy" (из диг. *kwi) и "k˳y" (из диг. *ku), но мне такие примеры неизвестны (в дигорском корпусе таких слов нет). Как бы то ни было, это не тот случай: в дигорском kurojnæ, dongurojnæ.
