### ISSUE TITLE
у сабэнтри коммент влез до сенс

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#102]
![image](https://user-images.githubusercontent.com/13102259/76622018-b60ff480-6541-11ea-958f-ad369508838c.png)
у сабэнтри посткоммент влез до сенс. я просто сделала его обычным посткомментом, нормально?

**Comment by solanum-tuberosum** [comment]
вот снова, я тоже поставила его как посткоммент к сенс
![image](https://user-images.githubusercontent.com/13102259/76636520-40645280-655a-11ea-9dd2-d90c2cce61ce.png)

**Comment by obelyaev** [comment]
Нормально.
