### ISSUE TITLE
постсабэнтри с примером? +странный хреф

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#103]
![image](https://user-images.githubusercontent.com/13102259/76736191-687ccd00-6777-11ea-9903-2ccebdde19ff.png)
Вот здесь сначала вроде по смыслу постсабэтри с примером. перед ним нет тире, а после него нет двоеточия. забить?

'+ есть перекрестная ссылка на слово kataej, но в словаре есть только kataj. сослалась пока на него. так и надо?

**Comment by obelyaev** [comment]
Зато есть точка с запятой, я думаю, нестрашно, что наша система ставит двоеточие.

Сослались правильно, это опечатка у Абаева, слова _катӕй_ не существует.
