### ISSUE TITLE
вопросик у ссылок в примерах

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#105]
![image](https://user-images.githubusercontent.com/13102259/76957571-137fb900-6927-11ea-935b-109e6b706a5c.png)
Как это сделать?

**Comment by obelyaev** [comment]
Никак. Я вообще не понимаю, к чему здесь вопрос. Вряд ли к источнику: я думаю, Абаев знал, откуда он брал примеры. Скорее это вопрос к интерпретации. Тогда можно сделать его посткомментом.

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/77729055-d8f4db00-700e-11ea-98e0-56cd432fe8cf.png)

**Comment by solanum-tuberosum** [comment]
Вот такое еще бывает. Так что видимо он регулярно ставит вопросики
![image](https://user-images.githubusercontent.com/13102259/77821010-b8ed1680-70f7-11ea-8e21-9cda7f166b28.png)

**Comment by solanum-tuberosum** [comment]
Осознала что бывает прекоммент к сорсу и записала вопросики туда.
Вопрос только про слово kʼūsk - это сорс или реф? (пока все желтое этого слова у меня записано просто в посткомменте к сенс с пустым рефом)
вообще по аналогии с сабэнтри, можно сделать возможность добавлять к лемме тоже сорс.
либо решить проблему, когда надо вставлять сорс просто в текстовые поля

**Comment by obelyaev** [comment]
> Осознала что бывает прекоммент к сорсу и записала вопросики туда.
> Вопрос только про слово kʼūsk - это сорс или реф? (пока все желтое этого слова у меня записано просто в посткомменте к сенс с пустым рефом)
> вообще по аналогии с сабэнтри, можно сделать возможность добавлять к лемме тоже сорс.
> либо решить проблему, когда надо вставлять сорс просто в текстовые поля

Мне кажется, так, как сейчас сделано, правильно. По сути это и есть посткоммент к значению, а не "источник значения" (значение ведь — это не пример).

**Comment by obelyaev** [comment]
> ![image](https://user-images.githubusercontent.com/13102259/77729055-d8f4db00-700e-11ea-98e0-56cd432fe8cf.png)

Вот для таких случаев в принципе теперь есть два варианта: PostComment к Example или PreComment к Source. Здесь по контексту ясно, что это скорее комментарий не к источнику, а к переводу примера, поэтому этот случай я передалал на PostComment + Source и сделал правильную пунктуацию.
