### ISSUE TITLE
комментарии к закрытым ишью

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#106]
иногда хочется что-то написать к уже закрытым ишью, но их не получается reopen
например здесь
https://github.com/abaevdict/abaevdict/issues/86
https://github.com/abaevdict/abaevdict/issues/83
(ну и здесь :) https://github.com/abaevdict/abaevdict/issues/93)

лучше делать аналогичные ишью в таком случае?

**Comment by obelyaev** [comment]
Если новая проблема, то аналогичные. А если нет, то я всё равно получаю уведомление о комментарии, так что всё ок :)
