### ISSUE TITLE
xref в переводе примера?..

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#109]
![image](https://user-images.githubusercontent.com/13102259/77149585-fd970300-6aa2-11ea-93d9-80abb85ae92a.png)
Очевидно, хреф тут никак не поставить... Забить?

**Comment by obelyaev** [comment]
Пока никак, да, потому что перевод идёт атрибутом, а не отдельным текстовым элементом (тогда в него можно было бы вставлять тэги). Само по себе, кстати, это м.б. было бы и разумно, но это потребует преобразования всех словарных статей. Это, наверное, можно сделать скриптом. Но нужно ли? Много Вам попадалось таких примеров?

**Comment by solanum-tuberosum** [comment]
Теперь в таких случаях можно поставить хреф. Поставила (единственная проблема -- на хреф не поставить смолкапс, но, наверно, пофиг)
