### ISSUE TITLE
cit и source/ref

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#111]
Что мы делаем вот в таких случаях?
![image](https://user-images.githubusercontent.com/13102259/77221933-8e331900-6b5f-11ea-9617-4a22fad8b918.png)
Я часто делаю два цита, а во втором делаю hidelanguage, чтобы перед вторым цитом поставить реф.
Сейчас вот я додумалась до того, что можно в текстовом поле (где обычно пишется само слово) вставлять реф
![image](https://user-images.githubusercontent.com/13102259/77221996-24673f00-6b60-11ea-9a4e-f3828c88e471.png)
А как вообще нужно действовать в таких случаях?

**Comment by jvsntsn** [comment]
Я делаю так, как описала ты. Если вставлять ref в текстовое поле cit'a, не повлияет ли это потом rкак-нибудь на поиск и выдачу результатов?
И кстати у нас же есть в cit'e возможность вставить source, только там source из части с примерами, может тогда добавить все источники?

**Comment by solanum-tuberosum** [comment]
О, а такое ишью уже было))
https://github.com/abaevdict/abaevdict/issues/47
но @obelyaev вы сказали, что сделали это, а у меня не получается так сделать все равно
Что и как нужно делать в итоге?

**Comment by obelyaev** [comment]
У меня всё работает :). Здесь надо просто добавить PostComment к form через меню. См., как я сделал с этим словом в базе. А вот вставлять ссылку прямо в текст формы не надо. Тогда действительно при поиске этот тэг окажется частью слова, что не очень хорошо.

**Comment by solanum-tuberosum** [comment]
Но в этом случае он показывается после формы и до перевода, а должен после перевода :(

![image](https://user-images.githubusercontent.com/13102259/86510471-8d658080-bdf8-11ea-8641-b2e25c0a8121.png)
![image](https://user-images.githubusercontent.com/13102259/86510474-98201580-bdf8-11ea-87b7-7642f47fda26.png)

**Comment by solanum-tuberosum** [comment]
Может сделать у form в cit'е и прекоммент, и посткоммент?)) потому что для случаев типа выше хочется как раз посткоммент (чтобы после form показывался). но прекоммент тоже нужен, я вот в этом слове (ʒynazyn) так сделала
![image](https://user-images.githubusercontent.com/13102259/86569728-86b14780-bf77-11ea-8ae0-57d399554764.png)
![image](https://user-images.githubusercontent.com/13102259/86569770-9d579e80-bf77-11ea-8f15-bb040965ec00.png)
Здесь посткоммент показывается нормально, но по-хорошему ему стоит стать прекомментом...
![image](https://user-images.githubusercontent.com/13102259/86569841-b52f2280-bf77-11ea-925a-a5d177cadcd8.png)

**Comment by jvsntsn** [comment]
![image](https://user-images.githubusercontent.com/48504970/86766762-a87ffc80-c053-11ea-928d-21ca3f732216.png)
плюс к тому, что прекоммент тоже не лишний в цитах.

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/87126330-ae185500-c294-11ea-9db9-1736cd41df72.png)
А здесь первые две желтые штуки по сути прекомменты (стоят до перевода), а вторые две -- посткомменты... (слово gaga)
