### ISSUE TITLE
cit (и cit)

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#113]
Умеем ли мы что-то делать со случаями, как на скрине?
Если делать второй язык цитом, то тлех будет ругаться на то, что у него нет своего примера? А если не делать, то мы теряем этот пример при поиске...
![image](https://user-images.githubusercontent.com/48504970/77351620-14618200-6d4f-11ea-91fc-8579516feeda.png)

**Comment by solanum-tuberosum** [comment]
Вот тут кстати было про пустые циты без форм https://github.com/abaevdict/abaevdict/issues/87
