### ISSUE TITLE
постсабэнтри или пример?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#114]
![image](https://user-images.githubusercontent.com/13102259/77433377-5989c080-6df0-11ea-8b31-81b7be8416e4.png)
с одной стороны здесь два перевода и они в одинарных кавычках, а с другой стороны оно не отделено тире. пока оставила в примерах (и оба перевода записала пока в один)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/86360363-edceb380-bc7a-11ea-9669-bf3776839e8e.png)

а здесь записала пока в постсабэнтри... не знаю, как правильно

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/87920798-6195fc00-ca82-11ea-8cdc-b1c92d7c18ff.png)
а здесь сделала первые два пресабэнтри, а желтое примером, хотя они друг от друга не отделены...

**Comment by solanum-tuberosum** [comment]
и здесь пока записала в постсабэнтри с посткомментом, хотя тире нет
![image](https://user-images.githubusercontent.com/13102259/89096096-748ec180-d3dc-11ea-806d-6519eedaadcc.png)

**Comment by obelyaev** [comment]
> ![image](https://user-images.githubusercontent.com/13102259/77433377-5989c080-6df0-11ea-8b31-81b7be8416e4.png)
> с одной стороны здесь два перевода и они в одинарных кавычках, а с другой стороны оно не отделено тире. пока оставила в примерах (и оба перевода записала пока в один)

Всё правильно сделали, только и здесь я бы тоже сказал, что это сабэнтри, а не пример. Мне кажется, не страшно, если в данном случае мы отступим от Абаева. Другой вопрос — хорошо бы как-то документировать эти расхождения. Чтобы было понятно, что это не случайная ошибка, а намеренно.
