### ISSUE TITLE
это же не сноска?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#115]
![image](https://user-images.githubusercontent.com/13102259/77433517-85a54180-6df0-11ea-862d-d02b6f98c2f1.png)
Слово kʼæm, внизу страницы нет сносок, но на всякий случай решила уточнить. пока записала просто "4" в текстовое поле к рефу.

**Comment by obelyaev** [comment]
Это, видимо, обозначает 4-е издание словаря. Но в списке литературы он и так указан как 4-е издание, так что это избыточно. Но пока можете оставить, как есть.
