### ISSUE TITLE
нужно мочь ставить не только реф, но и сорс! (в посткомменте к сенс)

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#118]
![image](https://user-images.githubusercontent.com/13102259/77436734-e46cba00-6df4-11ea-96e6-1b962a712224.png)
все что я могу сделать пока это сделать пустой цит с формой и сорс)) но он тогда еще почему-то курсивом выделяется.
в общем SOS нужно мочь ставить сорсы в разные места
(см. также https://github.com/abaevdict/abaevdict/issues/111)

**Comment by solanum-tuberosum** [comment]
Просто в этимологии тоже надо мочь ставить сорс...
![image](https://user-images.githubusercontent.com/13102259/77516842-209f2980-6e8c-11ea-86fd-8f38ca7081a8.png)
Слово kʼærnyx

**Comment by obelyaev** [comment]
Сделал это, теперь можно.
