### ISSUE TITLE
пример к посткомменту к лемме?))

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#119]
Не очень понимаю, что делать вот с этим
![image](https://user-images.githubusercontent.com/13102259/77515037-e7b18580-6e88-11ea-992c-e529477fff48.png)
![image](https://user-images.githubusercontent.com/13102259/77515045-eb450c80-6e88-11ea-948b-1e2c989549d8.png)

Сначала идет нормальный экзамплгруп, но потом уже идет как бы посткоммент к лемме, что вот и другое слово тоже употребляется. т.е. x˳ysnæg не похоже на постсабэнтри груп - потому что оно вообще другое. и потом к этому слову x˳ysnæg идет как бы свой пример... что делать?

**Comment by jvsntsn** [comment]
У меня тоже встретились примеры после явного посткоммента, причем с другими разделительными символами)))
![image](https://user-images.githubusercontent.com/48504970/78185153-4cfe0b80-7473-11ea-996f-59e7e301c0b8.png)
слово baergae

**Comment by solanum-tuberosum** [comment]
А прекоммент к экзампл груп не прокатит? У нас есть такое?

**Comment by solanum-tuberosum** [comment]
> У меня тоже встретились примеры после явного посткоммента, причем с другими разделительными символами)))
> ![image](https://user-images.githubusercontent.com/48504970/78185153-4cfe0b80-7473-11ea-996f-59e7e301c0b8.png)
> слово baergae

У меня сейчас тоже похожее встретилось
![image](https://user-images.githubusercontent.com/13102259/78219922-35517200-74c9-11ea-85f7-acbed6922aaa.png)
Я сделала прекоммент к примеру просто, форматирование даже нужное получается (ну кроме сорса/посткоммента к другому примеру, все еще пихаю просто все в поле сорс)
![image](https://user-images.githubusercontent.com/13102259/78220252-d8a28700-74c9-11ea-89a6-8344a1dbc991.png)


А в самом первом моем примере было немного другое, там пример же был вообще на другое слово. Т.е. по смыслу ближе к постсабэнтри, но не совсем

**Comment by obelyaev** [comment]
> Не очень понимаю, что делать вот с этим
> ![image](https://user-images.githubusercontent.com/13102259/77515037-e7b18580-6e88-11ea-992c-e529477fff48.png)
> ![image](https://user-images.githubusercontent.com/13102259/77515045-eb450c80-6e88-11ea-948b-1e2c989549d8.png)
> 
> Сначала идет нормальный экзамплгруп, но потом уже идет как бы посткоммент к лемме, что вот и другое слово тоже употребляется. т.е. x˳ysnæg не похоже на постсабэнтри груп - потому что оно вообще другое. и потом к этому слову x˳ysnæg идет как бы свой пример... что делать?

По идее то, что "Параллельное употребление" и далее — это прекоммент к последнему примеру / экзамплгруп, мне кажется. Можно ли это сделать в нашей системе и как это будет выглядеть?

**Comment by obelyaev** [comment]
> > У меня тоже встретились примеры после явного посткоммента, причем с другими разделительными символами)))
> > ![image](https://user-images.githubusercontent.com/48504970/78185153-4cfe0b80-7473-11ea-996f-59e7e301c0b8.png)
> > слово baergae
> 
> У меня сейчас тоже похожее встретилось
> ![image](https://user-images.githubusercontent.com/13102259/78219922-35517200-74c9-11ea-85f7-acbed6922aaa.png)
> Я сделала прекоммент к примеру просто, форматирование даже нужное получается (ну кроме сорса/посткоммента к другому примеру, все еще пихаю просто все в поле сорс)
> ![image](https://user-images.githubusercontent.com/13102259/78220252-d8a28700-74c9-11ea-89a6-8344a1dbc991.png)
> 
> А в самом первом моем примере было немного другое, там пример же был вообще на другое слово. Т.е. по смыслу ближе к постсабэнтри, но не совсем

Да, вот, я о том же и пишу: прекоммент к примеру. И в Юлином случае вроде бы тоже так можно.

**Comment by solanum-tuberosum** [comment]
> Не очень понимаю, что делать вот с этим
> ![image](https://user-images.githubusercontent.com/13102259/77515037-e7b18580-6e88-11ea-992c-e529477fff48.png)
> ![image](https://user-images.githubusercontent.com/13102259/77515045-eb450c80-6e88-11ea-948b-1e2c989549d8.png)
> 
> Сначала идет нормальный экзамплгруп, но потом уже идет как бы посткоммент к лемме, что вот и другое слово тоже употребляется. т.е. x˳ysnæg не похоже на постсабэнтри груп - потому что оно вообще другое. и потом к этому слову x˳ysnæg идет как бы свой пример... что делать?

Здесь все желтое положила в прекоммент к примеру.

**Comment by jvsntsn** [comment]
> У меня тоже встретились примеры после явного посткоммента, причем с другими разделительными символами)))
> ![image](https://user-images.githubusercontent.com/48504970/78185153-4cfe0b80-7473-11ea-996f-59e7e301c0b8.png)
> слово baergae

русский комментарий сделала прекомментом к примеру
