### ISSUE TITLE
странный xref

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#121]
![image](https://user-images.githubusercontent.com/48504970/77579156-e44ee600-6eea-11ea-8961-4eec23ce3e9a.png)

**Comment by solanum-tuberosum** [comment]
Кстати, по идее если у нас теперь есть посткоммент к лемме, куда можно вставлять что угодно, то отпадает необходимость мочь добавлять к лемме хреф?

**Comment by solanum-tuberosum** [comment]
А что теперь делать вот в таких случаях?
![image](https://user-images.githubusercontent.com/13102259/77645926-a6969f80-6f74-11ea-94c7-57e76c1acff7.png)
Делать просто хреф и забить на то, что мы теряем "и"? Или делать посткоммент к лемме с хрефом?

**Comment by obelyaev** [comment]
> Кстати, по идее если у нас теперь есть посткоммент к лемме, куда можно вставлять что угодно, то отпадает необходимость мочь добавлять к лемме хреф?

Мне кажется да, в таких случаях можно делать посткоммент к лемме.

А вот в последнем Вашем примере можно как угодно. Запятая не принципиальна.
