### ISSUE TITLE
формы после сабэнтри со знаком "="

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#122]
![image](https://user-images.githubusercontent.com/13102259/77627193-902e1b00-6f57-11ea-8f9e-5f0426bacad7.png)
пока поставила посткомментом... но вообще по-хорошему можно добавить поле "IronSynonym"))) у которого разделитель как раз будет с таким знаком. не знаю

Вот тут тоже такое было https://github.com/abaevdict/abaevdict/issues/88

**Comment by solanum-tuberosum** [comment]
Вот кстати "=" еще в таком случае встретилось
![image](https://user-images.githubusercontent.com/13102259/87338071-345ec080-c54d-11ea-9f18-28bd60951972.png)

**Comment by solanum-tuberosum** [comment]
> ![image](https://user-images.githubusercontent.com/13102259/77627193-902e1b00-6f57-11ea-8f9e-5f0426bacad7.png)
> пока поставила посткомментом... но вообще по-хорошему можно добавить поле "IronSynonym"))) у которого разделитель как раз будет с таким знаком. не знаю
> 
> Вот тут тоже такое было #88

обнаружила, что уже было такое ишью (https://github.com/abaevdict/abaevdict/issues/63#event-3060544281) и вроде действительно решили остановиться на посткомменте

но случай с "=" между сенсами (выше https://github.com/abaevdict/abaevdict/issues/122#issuecomment-657710873) все еще интересен

**Comment by obelyaev** [comment]
Да, такое было. Но это решение можно и пересмотреть. Давайте обсудим.

**Comment by obelyaev** [comment]
Сделаем PostComment всё-таки (кроме конопли, её мы отдельно обсудили).
