### ISSUE TITLE
пустое сабэнтри?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#123]
![image](https://user-images.githubusercontent.com/13102259/77629446-9376d600-6f5a-11ea-8a5c-46530998abf6.png)
Записала как сабэнтри, но почему там нет перевода? написать мб id. если это значит то же самое? или что это вообще?

**Comment by obelyaev** [comment]
Вообще странный пример, потому что _ӕндах_ — это собственно нитки, поэтому, если следовать буквальному переводу слова, получается "бумажные нитки нитки" :). Скорее похоже на то, что къӕскуы — это некий модификатор, прилагательная или форма в генитиве.

Вообще осетинско-русский словарь даёт другое перевод: "просмоленная толстая нитка, дратва" (whatever it is).

А в корпусе один пример, в сочетании _къӕскуы хӕдон_, т.е., видимо, рубашка (_хӕдон_) из таких ниток. Так что это действительно скорее всего прилагательное (или сущ. в двойной функции, что тоже нередко).

**Comment by obelyaev** [comment]
Добавить перевод "моток ниток".
