### ISSUE TITLE
source в ref?)

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#124]
![image](https://user-images.githubusercontent.com/48504970/77634705-71815180-6f62-11ea-95f6-9ca98f6e8900.png)
Дигорские сказки есть в поле source, но их нет в поле ref, а тут явный посткоммент к сенсу с рефами)))

**Comment by solanum-tuberosum** [comment]
Это же вот про это тоже https://github.com/abaevdict/abaevdict/issues/118, нет?

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/77820261-02d2fe00-70f2-11ea-8beb-86a6ad7e0e60.png)
Почему нельзя просто сделать возможность добавлять в текстовое поле сорс? так же как мы добавляем реф :(

**Comment by solanum-tuberosum** [comment]
У меня снова сорсы в этимологии
![image](https://user-images.githubusercontent.com/13102259/78111182-f3f78e80-7404-11ea-8fca-0af162062137.png)
Причем это вообще выглядит как сабэнтри... Что с ними делать?

**Comment by obelyaev** [comment]
Теперь это можно.

А насчёт сабэнтри — мы всё-таки не должны, как мне кажется, радикально менять структуру статьи, так что придётся оставить, как есть.

Вообще, кстати, не хотим ли мы осетинские примеры в этимологии отмечать тэгом?
