### ISSUE TITLE
спрятанный сабэнтри?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#126]
вот такое встретилось
![image](https://user-images.githubusercontent.com/13102259/77733058-40168d80-7017-11ea-82b8-ac0db7e24aaf.png)
решила, что пытаться сделать прекомменты к сенс это тупо и сделала вот так, сойдет?
![image](https://user-images.githubusercontent.com/13102259/77733109-5c1a2f00-7017-11ea-9b2d-4ebae496ed4d.png)

**Comment by obelyaev** [comment]
Вообще правда, это противоречит всей логике словаря, так что Вы сделали правильно. Но надо всё-таки где-то документировать наши "изменения" к Абаеву…
