### ISSUE TITLE
postcomment к переводу

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#127]
Возможно, мы это обсуждали (ткните тогда меня в нужное ишью :) ), но пока посткоммент к примеру ставится непосредственно после осетинского примера, а тут нужно после перевода) А прекоммент к источнику ставится в скобочках источника, что тоже не подходит...
![image](https://user-images.githubusercontent.com/48504970/77738507-02b6fd80-7021-11ea-8e94-8ce4afd17e03.png)

**Comment by solanum-tuberosum** [comment]
#94 это похоже на мои страдания))
в целом можно текущий посткоммент превратить в мидкоммент и добавить обычный посткоммент, который будет стоять до сенс, это решит много проблем
но не решит проблемы, когда у нас несколько сорсов в примерах
так что ужас

**Comment by solanum-tuberosum** [comment]
У Вадима похожее тоже встретилось
![image](https://user-images.githubusercontent.com/13102259/78358877-98700100-75bc-11ea-9e9a-5231d7ad8f30.png)

**Comment by solanum-tuberosum** [comment]
Еще пример Вадима
![image](https://user-images.githubusercontent.com/13102259/79104225-d3212880-7d76-11ea-8832-0b8bc062fb4f.png)

**Comment by obelyaev** [comment]
Эта проблема вроде бы решена, теперь "старый" посткоммент — это посткоммент к ExampleText, а если хочется поставить посткоммент после перевода, то надо делать его к Example. Правда, _бӕдул_ и "конь" получаются немного не такие, как у Абаева, т.к. у меня (в соответствии с другими статьями) сделано так, что если сорц следует за посткомментом, то они оба в скобках и между ними ставятся точка с запятой.

**Comment by solanum-tuberosum** [comment]
> Эта проблема вроде бы решена, теперь "старый" посткоммент — это посткоммент к ExampleText, а если хочется поставить посткоммент после перевода, то надо делать его к Example. Правда, _бӕдул_ и "конь" получаются немного не такие, как у Абаева, т.к. у меня (в соответствии с другими статьями) сделано так, что если сорц следует за посткомментом, то они оба в скобках и между ними ставятся точка с запятой.

https://github.com/abaevdict/abaevdict/issues/172
