### ISSUE TITLE
перевод

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#130]
Слово kʼoxar, как нормально перевести "сильная ступень огласовки"?
явно не strong step of vocalisation)))))))
![image](https://user-images.githubusercontent.com/13102259/77820400-26e30f00-70f3-11ea-8997-da28096ba9bb.png)

**Comment by jvsntsn** [comment]
https://en.wikipedia.org/wiki/Apophony
мб здесь можно найти ответ?

**Comment by obelyaev** [comment]
strong/full ablaut grade

strong/full grade of ablaut

**Comment by obelyaev** [comment]
https://en.wikipedia.org/wiki/Indo-European_ablaut
