### ISSUE TITLE
HideLanguage не должен прятать диалект?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#133]
Слово kʼūs, снова встретилось такое (https://github.com/abaevdict/abaevdict/issues/96#issuecomment-604879837_)
![image](https://user-images.githubusercontent.com/13102259/78012764-24c8bc80-734e-11ea-97b0-875cb20e4e14.png)
По идее в таких случаях просто ставить (диал) тупо и надо проставить язык и убрать его, но он убирает и помету диал.
-- либо отдельно завести HideLanguage&Dialect и HideLanguage (если встречаются такие случаи, когда надо скрыть и язык, и диалект)
-- либо просто сделать так, чтобы HideLanguage прятал только язык, но не трогал диалект

**Comment by solanum-tuberosum** [comment]
Вот еще встретилось. Во-первых, таких "диалектов" нет, надо добавить. ну и здесь тоже по-хорошему надо мочь прятать язык?..
![image](https://user-images.githubusercontent.com/13102259/86509614-f72e5c00-bdf1-11ea-9587-cc34bbb65ec8.png)

**Comment by solanum-tuberosum** [comment]
И вот еще (слово ʒyx), желтых штук тоже нет. и здесь тоже нужно прятать язык отдельно от диалектов?
![image](https://user-images.githubusercontent.com/13102259/86583613-3db7be00-bf8c-11ea-8330-f5051dcc9613.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/87326690-ba720b80-c53b-11ea-910c-0e88e64b34af.png)
здесь в первом случае писать просто прекомментом? (пока так сделала)
во втором случае надо, видимо, добавить это в диалект

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/87333723-32ddca00-c546-11ea-8cf0-ce86132114ca.png)
все еще нет мохев...

**Comment by obelyaev** [comment]
Добавить диалекты в список + сделать так, чтобы диалект не исчезал.

**Comment by obelyaev** [comment]
Всё это сделал.
