### ISSUE TITLE
пример на одно значение через двоеточие (не сабэнтри!)

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#134]
Вот такое встретилось
![image](https://user-images.githubusercontent.com/13102259/78015217-c8679c00-7351-11ea-95af-454a1843517d.png)

по идее это просто вторая сенсгруп. но он пишет просто словами, что это дигорское значение. и если не делать помету "д.", то мы можем это потерять (это вообще важно?)
и оформление примера похоже на пример для сабэнтри, но это не сабэнтри

Пока сделала так, нормально? прекоммент к сенс + сенс + экзампл груп
![image](https://user-images.githubusercontent.com/13102259/78015696-6fe4ce80-7352-11ea-8a23-aa805c1e42e0.png)

**Comment by obelyaev** [comment]
Мне кажетс, нормально, как сейчас, только пример надо отметить, как дигорский ("д.").
