### ISSUE TITLE
PostComment к лемме или кусок этимологии?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#135]
![image](https://user-images.githubusercontent.com/13102259/78112394-d4f9fc00-7406-11ea-9bca-f8b2efd5b441.png)
Там вот есть странный посткоммент, такие штуки вообще обычно писались в этимологии. Пока оставила посткомментом, но мб просто забить и запихнуть в этимологию?

**Comment by obelyaev** [comment]
Последнее предложение перенести в этимологию.

**Comment by obelyaev** [comment]
Сделать два примера, ко второму написать "ср." в PreComment.
