### ISSUE TITLE
МидСабэнтри?))

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#138]
Выделенные желтым штуки -- явные сабэнтри, но почему-то они распиханы внутри example group. Очень хочется сделать их обычными сабэнтри на привычном месте... Или забить и сделать, как у Абаева?
![image](https://user-images.githubusercontent.com/48504970/78381846-9e76d980-75de-11ea-8c47-967cfc4c7544.png)

**Comment by solanum-tuberosum** [comment]
Может быть, сделать постсабэнтри и к каждому постсабэнтри свой пример? Вроде выглядело бы тогда логично

**Comment by obelyaev** [comment]
Вы всё правильно сделали!
