### ISSUE TITLE
Номера значений и примеров

### ISSUE THREAD

**Issue by happyfruitcake** [obelyaev/abaevdict#142]
![iss4](https://user-images.githubusercontent.com/19610788/80959349-55998700-8e0f-11ea-917d-ff6bed3ce2a4.png)
Как в таком случае ставить номер перед значением и перед группой примеров?

**Comment by solanum-tuberosum** [comment]
У SensGroup и ExampleGroup есть поле number
![image](https://user-images.githubusercontent.com/13102259/80966338-04908f80-8e1d-11ea-919f-4abf931d66b7.png)
![image](https://user-images.githubusercontent.com/13102259/80966363-12deab80-8e1d-11ea-8edf-627446e44eb8.png)

NB! я заметила, что сейчас в словаре есть дубликаты
![image](https://user-images.githubusercontent.com/13102259/80966435-2e49b680-8e1d-11ea-8f20-4b755cb4e998.png)
Сначала нужно смотреть, нет ли уже слова в базе. Если есть, то изменять его, а не создавать новое. Например, я уже когда-то делала это слово, чтобы сделать на него хреф в моем слове.
![image](https://user-images.githubusercontent.com/13102259/80966511-52a59300-8e1d-11ea-8df2-c4d4604c2fd7.png)
И теперь нужно будет переделывать ссылки: смотреть, откуда идут ссылки из моей версии твоего слова, менять их на ссылки на твое новое слово, после этого мою версию твоего слова удалять.

**Comment by happyfruitcake** [comment]
Хорошо, спасибо!
