### ISSUE TITLE
Ссылка

### ISSUE THREAD

**Issue by happyfruitcake** [obelyaev/abaevdict#143]
![iss5](https://user-images.githubusercontent.com/19610788/80959540-b32dd380-8e0f-11ea-8a34-229411381a62.png)
![iss5a](https://user-images.githubusercontent.com/19610788/80959542-b45f0080-8e0f-11ea-9ac6-d1c7c69db138.png)

Можно ли так оформить? Или нужно как-то по-другому?

**Comment by solanum-tuberosum** [comment]
Мы обычно оформляли так, насколько я помню: Вс. Миллер (Ws. Miller. Gr. 64) ошибочно возводит к...

А это же сноска? Если, что сноски пишутся в двойных квадратных скобках: [[текст сноски]]

**Comment by happyfruitcake** [comment]
Хорошо, спасибо.
