### ISSUE TITLE
Что за диакритика?

### ISSUE THREAD

**Issue by happyfruitcake** [obelyaev/abaevdict#145]
![iss7](https://user-images.githubusercontent.com/19610788/81214104-048cbd00-8fe0-11ea-89b0-6d607afce973.png)

Какая тут диакритика над "g"?

**Comment by obelyaev** [comment]
ǧ

(теоретически могло бы быть ǵ, но это появляется только перед гласными переднего ряда или "y" (ы) без огубленности, а здесь не так)
