### ISSUE TITLE
PreSubEntry?

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#146]
![image](https://user-images.githubusercontent.com/48504970/83359732-cedfb780-a384-11ea-9203-95c3d3cb278d.png)
Вот тут выделенные штуки и по кавычкам, и особенно вторая штука по дигорскому варианту очень похожи на сабэнтри, хотя и располагаются в группе примеров. Я сделаю их как сабэнтри, так как их делать дольше и потом будет проще переделать в примеры?

**Comment by solanum-tuberosum** [comment]
См. еще https://github.com/abaevdict/abaevdict/issues/114#issuecomment-660907067

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/89014866-d25cd400-d31e-11ea-9b15-07c3e1ac32df.png)
Вот здесь пена изо рта выделена как отдельная экзампл груп. но по смыслу выглядит странно, потому что разные экзампл груп обычно на разные сенсы... пока сделала как у абаева, но мб здесь лучше сделать пресабэнтри?

**Comment by jvsntsn** [comment]
![image](https://user-images.githubusercontent.com/48504970/89199796-c475b000-d5b7-11ea-8bbc-0267d1a27707.png)
вот опять штуки в группе примеров, которые подозрительно похожи на пресабэнтри.... (особенно вторая с дигорским вариантом)

**Comment by jvsntsn** [comment]
и снова явный пресабэнтри в сомнительном месте, причем дальше группа примеров выделяется циферкой
![image](https://user-images.githubusercontent.com/48504970/89216038-66a29180-d5d2-11ea-9115-6d6744cd0560.png)

**Comment by jvsntsn** [comment]
и вот тут на мой взгляд явные пресабэнтри (особенно второе с двумя значениями -- это удобней сделать как пресабэнтри) и нормальных примеров нет...
![image](https://user-images.githubusercontent.com/48504970/89619847-5b33bc80-d897-11ea-9c4e-bef560ba53b4.png)

**Comment by obelyaev** [comment]
Всё это сделать сабэнтриями.

**Comment by jvsntsn** [comment]
Свои слова проверила, везде сабэнтри. Ира, как свое сделаешь, можешь закрывать)
