### ISSUE TITLE
чему верить?)

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#148]
В заголовке u обычная, а в первом же примере u длинная (и во втором тоже)
![image](https://user-images.githubusercontent.com/48504970/86508426-ab2ae980-bde8-11ea-841d-dbe46a56dc80.png)

**Comment by jvsntsn** [comment]
#139

**Comment by obelyaev** [comment]
Видимо, опечатка, здесь везде надо сделать долгое /u/.
