### ISSUE TITLE
посткоммент к лемме или к сенсгруп?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#152]
![image](https://user-images.githubusercontent.com/13102259/86893777-d2e0c100-c10a-11ea-8e48-3bdd2222e73e.png)
вот здесь по идее антоним должен идти как посткоммент к сенсгруп, но там в середине еще сабэнтригруп. а делать посткоммент к одной сабэнтри странно по смыслу. пока сделала как посткоммент к лемме. но мб стоит сделать посткоммент к сенсгрупп? и пусть стоит до этих сабэнтри?
кстати если делать посткоммент к лемме, то странное форматирование получается (и в русской, и в английской версии)
![image](https://user-images.githubusercontent.com/13102259/86893956-0d4a5e00-c10b-11ea-8207-ca2accb28674.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/87336619-cc0edf80-c54a-11ea-9fe4-eee65e492473.png)
вот здесь тоже по идее это не совсем посткоммент к пресабэнтри. и здесь не получится сделать посткоммент к лемме, потому что здесь идут примеры. пока сделала посткоммент к пресабэнтри...
что делать в таких случаях? забить?...

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/87566969-60ed1680-c6cc-11ea-8fe6-144023c64f1d.png)
и здесь. или это вообще неважно абсолютно и надо забить? на всякий случай пока кидаю в эту ветку такие случаи...

**Comment by obelyaev** [comment]
В первом можно оставить, как есть, а в 2 и 3 сделать посткомментами к SenseGroup.
