### ISSUE TITLE
прекоммент к сабэнтри или посткоммент к сенсу?

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#156]
Вот здесь выделенное желтым относится скорее к лемме (видимо, по большей части иронской) или скорее к комменту про дигорский и то, что там это слово редко значит потолок?
![image](https://user-images.githubusercontent.com/48504970/87128551-7a3f2e80-c298-11ea-8c0b-efeb52c2f41b.png)
В зависимости от того, куда это относится, я вижу два варианта: в первом случае сделать желтое прекомментом к сабэнтри, а во втором -- запихнуть все в посткоммент про дигорский
(пока наверное сделаю первый вариант, его будет проще исправить...)

**Comment by jvsntsn** [comment]
UPD
![image](https://user-images.githubusercontent.com/48504970/87131003-71e8f280-c29c-11ea-8c14-1d48bffb3454.png)
судя по этому примеру, желтое и выражения после относятся к дигорскому
тогда сделать все посткомментом? или оставить прекоммент и сабэнтри? но тогда было бы неплохо как-то отметить, что сабэнтри дигорские?

**Comment by obelyaev** [comment]
В первый раз было правильно (прекоммент к сабэнтри), т.к. эти слова не собственно дигорские.
