### ISSUE TITLE
женские (и мои) причитания

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#157]
![image](https://user-images.githubusercontent.com/48504970/87141706-1e7ea080-c2ac-11ea-87e8-95dedbe8697a.png)
считать ли женские причитания отдельным источником?))
Если нет, то считаем их прекомментом к источнику, но в таком случае прекомменту очень нужен разделитель ; (тут могла быть отсылка на ишью про это, @solanum-tuberosum, возможно, ты помнишь номер?)

**Comment by jvsntsn** [comment]
так-так-так, я прочитала важный коммент https://github.com/abaevdict/abaevdict/issues/94#issuecomment-652500429 после того, как сделала ишью; тогда это закрываю)

**Comment by jvsntsn** [comment]
Итак, я попыталась сделать пост коммент отдельный и потом источник, но меня тлех упорно не хочет так делать и уже третий раз выкидывает меня после того, как я добавляю источник после посткоммента

**Comment by jvsntsn** [comment]
причем это кажется странным, потому что я наверняка уже делала примеры с посткомментом и источником, и меня не выкидывало...
может быть такое, что тлеху не нравится, что я сначала делаю все нужные поля, а потом заполняю их?

**Comment by solanum-tuberosum** [comment]
Про посткомменты и сорсы: мой опыт отражен вот здесь)) https://github.com/abaevdict/abaevdict/issues/151 возможно, я тут что-то не так тоже сделала

Про разделитель ; у прекоммента я видимо действительно имела в виду случаи с сорсами! https://github.com/abaevdict/abaevdict/issues/112#issuecomment-654401742 
Но если это все по-другому теперь делается, то такой разделитель уже не нужен?

В общем, кажется, мы не до конца привыкли к новым примерам и везде путаемся и не все получается))

**Comment by obelyaev** [comment]
А какое это слово? Сейчас посмотрю.

По смыслу это, как мне кажется, скорее прекоммент к сорсу :)

**Comment by jvsntsn** [comment]
Это car
Вот если прекоммент, тогда нужен разделитель ;

**Comment by obelyaev** [comment]
Да, действительно, вылетает!

Видимо, я в какой-то момент что-то сломал своими скриптами. Сейчас буду разбираться.

**Comment by obelyaev** [comment]
Теперь должно работать, была ошибка в скрипте.

Точку запятой сделаю сейчас, если никто не залогинен.

**Comment by jvsntsn** [comment]
Спасибо!
Я вышла

**Comment by obelyaev** [comment]
Вроде сделал, и в этом примере именно поставил PreComment, semicolon after. Проверьте, пожалуйста. Если всё ОК, можете закрыть ишью :)
