### ISSUE TITLE
сенсгруп или пресабэнтри?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#159]
![image](https://user-images.githubusercontent.com/13102259/87337771-a5ea3f00-c54c-11ea-8d4c-f64948028b43.png)
вот здесь странно. с одной стороны тут явно нумерация сенсгруп. но у второй "прекоммент" очень похож на сабэнтри с дигорской формой и всем таким. что сделать? прекоммент к сенсгруп или пресабэнтри?

**Comment by obelyaev** [comment]
Сделать это просто вторым значением, а gædy-bælas — subentry, про которое будет сказано "букв. кошачье дерево".
