### ISSUE TITLE
отсылки

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#160]
Слово cal имеет вот такую этимологию и отсылает вот к такому слову "какой":
![image](https://user-images.githubusercontent.com/48504970/87382677-30a85980-c5a0-11ea-9162-7b6fd7cac162.png)
Однако вхождения cavar в словарь нет, есть только cavaer, у него вот такая этимология:
![image](https://user-images.githubusercontent.com/48504970/87382743-559ccc80-c5a0-11ea-8100-8eeca61ecf22.png)
Вопрос знатокам: можно ли в таком случае в cal cослаться на cavaer, а на на саvar?

**Comment by obelyaev** [comment]
Это почти точно опечатка.
