### ISSUE TITLE
Второе значение у формы

### ISSUE THREAD

**Issue by happyfruitcake** [obelyaev/abaevdict#163]
Можно второе значение просто через запятую в перевод или как-то можно добавить второй перевод? Извините, если задаю вопросы, на которые уже были даны ответы, в старых issues не нашел.

![iss9](https://user-images.githubusercontent.com/19610788/87861839-d79b4580-c952-11ea-8171-01caae568cb6.png)

**Comment by solanum-tuberosum** [comment]
Просто добавь к одному cit'у две формы :)

**Comment by happyfruitcake** [comment]
![brain](https://user-images.githubusercontent.com/19610788/87861911-89d30d00-c953-11ea-8aa7-34d392c5ab0f.jpg)
