### ISSUE TITLE
нет языка

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#164]
![image](https://user-images.githubusercontent.com/48504970/88055416-a182df00-cb67-11ea-96a5-dd47b1ffa8dd.png)
мандинго

**Comment by jvsntsn** [comment]
еще двух языков нет -- шорск. и зап.черк. (просто черк. есть, к слову)
![image](https://user-images.githubusercontent.com/48504970/88206414-dde13880-cc56-11ea-81cb-c028a1a7a313.png)

**Comment by solanum-tuberosum** [comment]
нубийский (слово gædy 1)
![image](https://user-images.githubusercontent.com/13102259/88294867-67e7da80-cd05-11ea-843e-bb4e541c931b.png)

**Comment by jvsntsn** [comment]
еще нет просто индийского
![image](https://user-images.githubusercontent.com/48504970/88481306-3d935880-cf63-11ea-8141-82bc3f70947e.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/89025661-e9f08880-d32f-11ea-8258-f5db0de17c78.png)
Ванеци (слово fynʒ)

**Comment by obelyaev** [comment]
> ![image](https://user-images.githubusercontent.com/48504970/88055416-a182df00-cb67-11ea-96a5-dd47b1ffa8dd.png)
> мандинго

мандинка

**Comment by obelyaev** [comment]
> еще нет просто индийского
> ![image](https://user-images.githubusercontent.com/48504970/88481306-3d935880-cf63-11ea-8141-82bc3f70947e.png)

Посмотреть, что имеется в виду.

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/90145797-fb527f80-dd88-11ea-9414-90ac58ce1d61.png)
не нашла япон.

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/90233239-7cac1f80-de26-11ea-8066-2a6b036598c8.png)
не нашла швед.

**Comment by jvsntsn** [comment]
загадочный будух...
![image](https://user-images.githubusercontent.com/48504970/90320507-9e9ec280-df4a-11ea-91bc-72048ed86244.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/90627848-3a6b4f80-e225-11ea-8c64-a7307ae67787.png)

**Comment by solanum-tuberosum** [comment]
Слово fijjag
![image](https://user-images.githubusercontent.com/13102259/91167801-39cb3100-e6dd-11ea-93c2-49d219e66b00.png)

**Comment by jvsntsn** [comment]
загадочный брег. в слове daes
![image](https://user-images.githubusercontent.com/48504970/91282288-d4854780-e791-11ea-97dc-eb7aa9432873.png)

и не может ли это быть брет.?..

**Comment by solanum-tuberosum** [comment]
fīdyn
![image](https://user-images.githubusercontent.com/13102259/91284583-c258d880-e794-11ea-86c5-612810c87a28.png)

**Comment by solanum-tuberosum** [comment]
> загадочный брег. в слове daes
> ![image](https://user-images.githubusercontent.com/48504970/91282288-d4854780-e791-11ea-97dc-eb7aa9432873.png)
> 
> и не может ли это быть брет.?..

@jvsntsn Похоже на брет. в принципе

**Comment by jvsntsn** [comment]
там же семнанский диалект
![image](https://user-images.githubusercontent.com/48504970/91286288-ecab9580-e796-11ea-9965-053fda78573d.png)

**Comment by jvsntsn** [comment]
> fīdyn
> ![image](https://user-images.githubusercontent.com/13102259/91284583-c258d880-e794-11ea-86c5-612810c87a28.png)

пехл турф есть

**Comment by solanum-tuberosum** [comment]
> > fīdyn
> > ![image](https://user-images.githubusercontent.com/13102259/91284583-c258d880-e794-11ea-86c5-612810c87a28.png)
> 
> пехл турф есть

упс сорри, спс

**Comment by jvsntsn** [comment]
вот такой еще, я даже не знаю, что имеется в виду...
![image](https://user-images.githubusercontent.com/48504970/95651923-22fa6580-0af6-11eb-88c1-ed1761758e4b.png)

**Comment by jvsntsn** [comment]
н.гр и семит., слово ʒæk'ūl
![image](https://user-images.githubusercontent.com/48504970/95652495-1415b200-0afa-11eb-8be0-6fe929556724.png)

**Comment by jvsntsn** [comment]
в этом же слове есть про гр., и в словах есть разница между гр. и н.гр.
![image](https://user-images.githubusercontent.com/48504970/95652628-2512f300-0afb-11eb-8181-7c011db5a5b1.png)

**Comment by obelyaev** [comment]
> Слово fijjag
> ![image](https://user-images.githubusercontent.com/13102259/91167801-39cb3100-e6dd-11ea-93c2-49d219e66b00.png)

А как тут быть с падежом? Надо добавить, видимо, HideDialect?

**Comment by obelyaev** [comment]
> загадочный брег. в слове daes
> ![image](https://user-images.githubusercontent.com/48504970/91282288-d4854780-e791-11ea-97dc-eb7aa9432873.png)
> 
> и не может ли это быть брет.?..

Это точно "брет.", бретонский.

**Comment by obelyaev** [comment]
> вот такой еще, я даже не знаю, что имеется в виду...
> ![image](https://user-images.githubusercontent.com/48504970/95651923-22fa6580-0af6-11eb-88c1-ed1761758e4b.png)

Это ср. инд., т.е. средние индоарийские.

**Comment by obelyaev** [comment]
> в этом же слове есть про гр., и в словах есть разница между гр. и н.гр.
> ![image](https://user-images.githubusercontent.com/48504970/95652628-2512f300-0afb-11eb-8181-7c011db5a5b1.png)

Добавил н.гр., а гр. и так есть. Вообще всё добавил, закрываю :)

**Comment by jvsntsn** [comment]
> > Слово fijjag
> > ![image](https://user-images.githubusercontent.com/13102259/91167801-39cb3100-e6dd-11ea-93c2-49d219e66b00.png)
> 
> А как тут быть с падежом? Надо добавить, видимо, HideDialect?

я бы это сделала с новым цитом после слова "диалектов" и все спрятала бы, да, нужен hide dialect)

**Comment by jvsntsn** [comment]
> ![image](https://user-images.githubusercontent.com/48504970/88055416-a182df00-cb67-11ea-96a5-dd47b1ffa8dd.png)
> мандинго

@obelyaev мандинка все еще нет в списке языков: 
 ![image](https://user-images.githubusercontent.com/48504970/98651332-2a0dd100-234b-11eb-872b-6013768c1563.png)
