### ISSUE TITLE
пример употребления русского соответствия: как переводить?

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#167]
Вот тут выделенное желтым явно тянет на пример употребления приведенных русских слов, в связи с чем "тупо" перевести их на английский кажется сомнительной идеей?.. Я бы, наверное, оставила в английской версии русскую часть как пример, а после добавила бы перевод...
![image](https://user-images.githubusercontent.com/48504970/88839612-f962bb00-d1e3-11ea-9c83-74501614f57c.png)

**Comment by obelyaev** [comment]
Сделать cit с переводом в английской версии: _lapotki čukavye_ `…'
