### ISSUE TITLE
посткоммент к сорс))

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#168]
Встретилось вот такое
![image](https://user-images.githubusercontent.com/13102259/88883704-a9b0dd80-d23d-11ea-9542-559140859bf5.png)
Я решила (и предлагаю) забить и поставить это прекомментом к сорс.

**Comment by solanum-tuberosum** [comment]
И вот еще. Что здесь сделать? Слово fyd 3
![image](https://user-images.githubusercontent.com/13102259/89884735-9e14cd80-dbd2-11ea-9d7f-c59d43623a06.png)

**Comment by obelyaev** [comment]
Перенести в PostComment к Example, ничего страшного.
