### ISSUE TITLE
два subentry или один subentry + lemma variant?

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#169]
![image](https://user-images.githubusercontent.com/48504970/88895102-5c3e6b80-d251-11ea-97ab-35811d1cdc7d.png)
интуитивно я за второй вариант, но лучше уточнить у тех, кто знает осетинский лучше меня :)

**Comment by obelyaev** [comment]
Одно сабэнтри это (фон. варианты).
