### ISSUE TITLE
что за буква?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#193]
![image](https://user-images.githubusercontent.com/13102259/98109265-57233500-1eae-11eb-8b29-fa40e52db6f4.png)
Слово fætæn

я нашла букву "торн" þ, но на ней нет черточки..
еще есть ƀ "б" со штрихом, но это менее похоже

**Comment by jvsntsn** [comment]
кажется, я нашла эту букву))
Ꝥ ꝥ
