### ISSUE TITLE
PostComment к PostSubentry?

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#74]
![image](https://user-images.githubusercontent.com/48504970/65901575-29251480-e3c1-11e9-82a8-30f99c1356ad.png)
вот тут bavdælyn аmа... я сделала postsubentry, потому что после него двоеточие и пример, а потом очень хочется сделать посткоммент к всей сабэнтри групп, потому что посткоммент к примеру вставляется между переводом и источником, что не очень...

**Comment by jvsntsn** [comment]
слово ævdælyn

**Comment by obelyaev** [comment]
Мы вроде бы решили это делать как PostComment ко всей лемме в #45

**Comment by jvsntsn** [comment]
Посткоммент ко всей лемме очень нужен, потому что он бывает вот такой очень внушительный
![image](https://user-images.githubusercontent.com/48504970/66336605-17ee8180-e946-11e9-8a17-e303822f49ad.png)
(слово ævdīw)

**Comment by jvsntsn** [comment]
еще заодно нужен посткоммент к переводу)) чтобы запихнуть в него (?) из примера перед посткомментом ко всей лемме))

**Comment by obelyaev** [comment]
Посткоммент к лемме я сделал, а вот тут не знаю, как быть, потому что делать PostPostComment или MidComment мне кажется перебором. Надо подумать об этом, но в принципе для штук типа "(?)" я не вижу криминала в том, чтобы писать их *внутри* перевода.

**Comment by obelyaev** [comment]
Здесь можно писать внутри кавычек, скорее всего ничего страшного.
