### ISSUE TITLE
сл: что ето токое

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#76]
![image](https://user-images.githubusercontent.com/48504970/66037849-32c19000-e519-11e9-9e7c-fdeb3f2a2e28.png)
Мы с Ирой поняли, что не знаем, как переводить сл. в ссылках на литературу))) и никак до этого момента не переводили)))

**Comment by obelyaev** [comment]
Это ff. Т.е. страница такая-то и следующие.
