### ISSUE TITLE
кавычки в sense + перевод

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#77]
![image](https://user-images.githubusercontent.com/13102259/66146541-a648c780-e615-11e9-9607-431fa784e292.png)
Если писать нужные кавычки, то вокруг них же все равно появятся кавычки. Забить?
и я не знаю как это слово вообще перевести...

**Comment by solanum-tuberosum** [comment]
Здесь тоже не те кавычки, забить?
![image](https://user-images.githubusercontent.com/13102259/66190516-dc795c00-e694-11e9-8d15-e5f019e95e41.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/66265521-d87a4500-e820-11e9-9608-3778d31311db.png)
Очевидно, что это сабентри -- пример идет после двоеточия
Мб сделать возможность выбирать тип кавычек для поля Sense? чтобы автоматически ставились одинарные, но если нужно, то мы могли бы поставить двойные

**Comment by solanum-tuberosum** [comment]
а вот такие кавычки в примерах!
![image](https://user-images.githubusercontent.com/13102259/66762188-2a207080-eeae-11e9-9766-eede0a32d909.png)
мб правда везде сделать стандартные (для каждого типа) по умолчанию, но сделать возможность их менять?

**Comment by jvsntsn** [comment]
![image](https://user-images.githubusercontent.com/48504970/66911230-c1093c00-f018-11e9-86b3-f27bd900a161.png)
и вообще насколько это все тянет на сабэнтри?

**Comment by jvsntsn** [comment]
![image](https://user-images.githubusercontent.com/48504970/66912829-0418de80-f01c-11e9-950e-d3532ede9334.png)
а еще есть и такие кавычки, и такие!

**Comment by solanum-tuberosum** [comment]
Вот еще не те кавычки в сабэнтри
![image](https://user-images.githubusercontent.com/13102259/67023173-06a63180-f10b-11e9-8a33-8e6305da259d.png)

**Comment by solanum-tuberosum** [comment]
В примере два перевода с другими кавычками)))
![image](https://user-images.githubusercontent.com/13102259/67755402-2281cf80-fa49-11e9-8547-519945119c00.png)
+ перс (диал) #42

**Comment by obelyaev** [comment]
Хорошо, вы меня убедили, сделаю переключатель кавычек.

**Comment by obelyaev** [comment]
> ![image](https://user-images.githubusercontent.com/48504970/66911230-c1093c00-f018-11e9-86b3-f27bd900a161.png)
> и вообще насколько это все тянет на сабэнтри?

Здесь, кстати, Вы сделали равно и всё, что после, комментарием. Это не совсем верно, т.к. в кавычках перевод основного выражения (и второго тоже). По идее то, что после знака равенства, — комментарий к форме, т.е. иронский аналог дигорского выражения. Но как это реализовать нормально, я не знаю. Может быть, в данном случае у всей сабэнтри будет форма "ХХХ = ХХХ" с переводом?

**Comment by obelyaev** [comment]
Переключатели я сделал: у Sense DoubleQuotes, у Example — SingleQuotes.
