### ISSUE TITLE
subentry и xref'ы: новые слова

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#78]
Мы не обсуждали пока наши новые слова.

В одном слове есть вот такая ссылка в этимологии:
![image](https://user-images.githubusercontent.com/13102259/66148964-c0d16f80-e61a-11e9-8451-a2fbb4f9fde2.png)
Но самого слова kaedaem нет в словаре. Оно присутствует в виде SubEntry к слову kaed.

Что делать с таким? Просто помечать как new, а потом что-то решить? по идее надо тогда написать перевод + ссылку на kaed?

**Comment by obelyaev** [comment]
Думаю да, именно так, как Вы написали. Перевод и ссылка на kæd. Иначе это будет не очевидно пользователям словаря.
