### ISSUE TITLE
xref и новые слова: уточнение

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#79]
Юлино (@jvsntsn ) слово ændæra (стр. 127 в pdf)
Слова kaeddaera в словаре нет, но на него идет xref:
![image](https://user-images.githubusercontent.com/13102259/66149483-e612ad80-e61b-11e9-9a18-d9d9854f369b.png)
Все равно делать ссылку именно на него? Мб сделать ссылку на kaed и daer отдельно, чтобы не плодить сущности? (типа хреф:kaed-хреф:daer-a)
(слово ævæʒa в словаре есть, если что)

**Comment by solanum-tuberosum** [comment]
Еще одна вещь.

В словаре есть такое слово:
![image](https://user-images.githubusercontent.com/13102259/67088685-76212d00-f1ae-11e9-8a28-7c2183b52f9d.png)

У @jvsntsn оно было записано вот так в этимологии:
![image](https://user-images.githubusercontent.com/13102259/67088720-8afdc080-f1ae-11e9-9e9b-64adbbdfc53a.png)

Но у меня оно выглядит по-другому + в словаре не так
![image](https://user-images.githubusercontent.com/13102259/67088761-9fda5400-f1ae-11e9-9d52-35b6f0786a43.png)

Я поменяла в словаре baerc(ae) на baerc просто. Но @jvsntsn надо будет, видимо, как-то исправить у себя этимологию.

**Comment by obelyaev** [comment]
> Еще одна вещь.
> 
> В словаре есть такое слово:
> ![image](https://user-images.githubusercontent.com/13102259/67088685-76212d00-f1ae-11e9-8a28-7c2183b52f9d.png)
> 
> У @jvsntsn оно было записано вот так в этимологии:
> ![image](https://user-images.githubusercontent.com/13102259/67088720-8afdc080-f1ae-11e9-9e9b-64adbbdfc53a.png)
> 
> Но у меня оно выглядит по-другому + в словаре не так
> ![image](https://user-images.githubusercontent.com/13102259/67088761-9fda5400-f1ae-11e9-9d52-35b6f0786a43.png)
> 
> Я поменяла в словаре baerc(ae) на baerc просто. Но @jvsntsn надо будет, видимо, как-то исправить у себя этимологию.

Это вообще нестрашно, я так думаю. Слово-то всё равно одно. Разве что Абаев хотел подчеркнуть, что там тоже в дигорском будет лягушка. Можно в скобочках это добавить.

**Comment by obelyaev** [comment]
> Юлино (@jvsntsn ) слово ændæra (стр. 127 в pdf)
> Слова kaeddaera в словаре нет, но на него идет xref:
> ![image](https://user-images.githubusercontent.com/13102259/66149483-e612ad80-e61b-11e9-9a18-d9d9854f369b.png)
> Все равно делать ссылку именно на него? Мб сделать ссылку на kaed и daer отдельно, чтобы не плодить сущности? (типа хреф:kaed-хреф:daer-a)
> (слово ævæʒa в словаре есть, если что)

Какой смысл так делать? Ведь кæддæра вовсе не деривируется композиционально из значений "когда" и "тоже" (во всяком случае читателю это не очевидно). Всё-таки надо добавить ссылку на него, а вот что там писать — другой вопрос.
