### ISSUE TITLE
еще один issue про xref

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#80]
У меня стоит ссылка на aeppyn:
![image](https://user-images.githubusercontent.com/13102259/66150264-70a7dc80-e61d-11e9-9a33-937dec83de84.png)

Но оно выглядит вот так:
![image](https://user-images.githubusercontent.com/13102259/66150277-7bfb0800-e61d-11e9-8b9d-69647fc0ed98.png)

Потому что слово в словаре выглядит вот так:
![image](https://user-images.githubusercontent.com/13102259/66150218-5b32b280-e61d-11e9-8f03-53a778371bd4.png)

Может быть, записать его как aeppyn (lemmavariant: aeppyndaer)? @jvsntsn

**Comment by solanum-tuberosum** [comment]
Еще вот здесь вопрос: в этимологии слова kæf и q˳yn понятны, они есть в словаре. А просто слова dar нет. Надо ли где-то сослаться на изначальный глагол в скобках? или забить? пока я поставила хрефы только на первые два слова
![image](https://user-images.githubusercontent.com/13102259/66251463-009e7100-e759-11e9-88dc-aba2fa43f31e.png)

**Comment by obelyaev** [comment]
> У меня стоит ссылка на aeppyn:
> ![image](https://user-images.githubusercontent.com/13102259/66150264-70a7dc80-e61d-11e9-9a33-937dec83de84.png)
> 
> Но оно выглядит вот так:
> ![image](https://user-images.githubusercontent.com/13102259/66150277-7bfb0800-e61d-11e9-8b9d-69647fc0ed98.png)
> 
> Потому что слово в словаре выглядит вот так:
> ![image](https://user-images.githubusercontent.com/13102259/66150218-5b32b280-e61d-11e9-8f03-53a778371bd4.png)
> 
> Может быть, записать его как aeppyn (lemmavariant: aeppyndaer)? @jvsntsn

Да, я думаю LemmaVariant с параметром InParentheses. Будет нормально выглядеть.

**Comment by obelyaev** [comment]
> Еще вот здесь вопрос: в этимологии слова kæf и q˳yn понятны, они есть в словаре. А просто слова dar нет. Надо ли где-то сослаться на изначальный глагол в скобках? или забить? пока я поставила хрефы только на первые два слова
> ![image](https://user-images.githubusercontent.com/13102259/66251463-009e7100-e759-11e9-88dc-aba2fa43f31e.png)

Вообще по идее надо бы на daryn ссылку, да. Абаев, конечно, считает, что любой иранист знает, что это за основа dar-. Это, пожалуй, так, но могут быть и другие пользователи. Я бы в скобках написал "см. daryn".
