### ISSUE TITLE
воистину демоническое слово

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#81]
![image](https://user-images.githubusercontent.com/48504970/66336920-bbd82d00-e946-11e9-8f78-ea0d333f3090.png)
тут в выделенном примере прямо в источнике еще три строчки комментария... видимо, 
это надо будет запихнуть в какой-то из посткомментов?))

**Comment by jvsntsn** [comment]
или забить и записать это все в текстовое поле в сорс?))) (пока я так и сделала)
upd: так не получится, потому что некуда будет пихать английский перевод, но пока все равно оставила в сорсе

**Comment by jvsntsn** [comment]
еще в этом слове в этимологии есть ссылки на литературу из источников
![image](https://user-images.githubusercontent.com/48504970/66900183-03288280-f005-11e9-9b5d-41dd73786006.png)

**Comment by obelyaev** [comment]
> еще в этом слове в этимологии есть ссылки на литературу из источников
> ![image](https://user-images.githubusercontent.com/48504970/66900183-03288280-f005-11e9-9b5d-41dd73786006.png)

Это я уже сделал.

**Comment by obelyaev** [comment]
> или забить и записать это все в текстовое поле в сорс?))) (пока я так и сделала)
> upd: так не получится, потому что некуда будет пихать английский перевод, но пока все равно оставила в сорсе

А вот это действительно проблема, о которой я не думал, когда ранее писал, что можно просто всё писать в поле Text в Source. Мне кажется, надо сделать отдельно Text_RU и Text_EN, к сожалению. Всё равно, даже если мы заведём источники для всего и вся и придумаем ещё какой-нибудь коммент и т.д., наверняка где-нибудь попадутся ссылки со штуками типа "т.", "с.", которые нужно переводить.

Проблема только в том, что надо как-то переносить из русского в английский. Можно написать скрипт, но лучше я сделаю так: добавлю поле Text_EN. Оно будет заменять русское, только если не пустое. Это в большинстве случаев ускорит работу.

**Comment by obelyaev** [comment]
На всякий случай и в Source, и в ref добавил поле Text_EN, по умолчанию его не видно, но если вдруг по-английски надо написать что-то другое, его можно использовать. Пока пусть будет так, а дальше посмотрим. Не закрываю этот issue.

**Comment by obelyaev** [comment]
Сделать PostComment к Source.

**Comment by jvsntsn** [comment]
> ![image](https://user-images.githubusercontent.com/48504970/66336920-bbd82d00-e946-11e9-8f78-ea0d333f3090.png)
> тут в выделенном примере прямо в источнике еще три строчки комментария... видимо,
> это надо будет запихнуть в какой-то из посткомментов?))

сделала посткоммент к примеру, следовательно это идет перед источником; сорсы в этимологии поправила
