### ISSUE TITLE
ссылка к примерам: перевод

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#82]
![image](https://user-images.githubusercontent.com/13102259/66762102-ff361c80-eead-11e9-8f17-8d85f6fd6106.png)
как вот это будет выглядеть в английской версии? что с этим делать?

**Comment by obelyaev** [comment]
Вот для этого я сделал поле Text_EN, которое можно заполнить, если надо переводить текст у источника.
