### ISSUE TITLE
Абаев сам ссылается на слова, которых нет: как это?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#83]
Слово kaenyn, здесь явно должен быть xref на все. Но слова kalmaerzaen нет в словаре. Одно дело когда мы сами рандомно решаем поставить xref, а слова нет, а тут сам Абаев так делает. Чем он руководствовался?))) Должна же быть логика. Штоделоть
![image](https://user-images.githubusercontent.com/13102259/66922540-ed7c8280-f02f-11e9-8995-f362624a6844.png)

У Юли тоже такое было @jvsntsn

**Comment by obelyaev** [comment]
Вы представляете, как словарь составлялся в старые времена? Была огромная картотека, заполнялась вручную. Конечно, что-то он упустил. Думаю, ссылку надо поставить, а что там написать — посмотрим. Можно просто перевод хотя бы, уже будет лучше, чем есть.

**Comment by solanum-tuberosum** [comment]
Кажется, нашла еще пустое слово
![image](https://user-images.githubusercontent.com/13102259/75474197-9a381a80-59a7-11ea-9411-cf5980e4e811.png)
Ссылка на kūrdiat
И здесь тоже
![image](https://user-images.githubusercontent.com/13102259/75474335-de2b1f80-59a7-11ea-9f06-c6b0e82d6db1.png)
Слово kūryn есть, а отдельно слова kūrdiat нет. Есть только kūrdiad в постсабэнтри.
![image](https://user-images.githubusercontent.com/13102259/75474410-0155cf00-59a8-11ea-86d7-67b1149e5080.png)
