### ISSUE TITLE
что есть cit (если язык не жирненький)

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#85]
![image](https://user-images.githubusercontent.com/13102259/66923995-7d233080-f032-11e9-89f0-ff6e07705dad.png)
Вот здесь язык не жирненький, надо ли делать cit?
В некоторых словах (сейчас не вспомню где) мне показалось, что есть следующая логика: если Абаев не уверен, что этимология адекватна, то он не делал жирные языки, а в том же слове делал другие, про которые он, видимо, был уверен.
Но @jvsntsn сказала, что она вообще все языки клала в cit (пофиг, жирное или нет, вдруг неправильно распозналось).
Што делоть?

(У меня была следующая логика. Допустим, мы хотим найти все русские слова, связанные с осетинским, делаем это по cit'ам. Тогда мы не хотим видеть в этих cit'ах откровенный бред.)

**Comment by solanum-tuberosum** [comment]
Вот например наткнулась просто на слово далее: одно слово жирное, другое нежирное
![image](https://user-images.githubusercontent.com/13102259/66924793-f0797200-f033-11e9-9075-575f286760ed.png)
Здесь явно же есть логика
Тогда мб не делать cit'ы, когда явно понятно, что вряд ли с этим словом что-то связано. А если не особо понятно, и ничего специально про это не написано (как в предыдущем посте), то делать все равно?

**Comment by solanum-tuberosum** [comment]
Вот еще
![image](https://user-images.githubusercontent.com/13102259/66926423-ad6cce00-f036-11e9-9a7d-0ddef449260f.png)

**Comment by solanum-tuberosum** [comment]
А вот здесь надо делать циты?... Слово kærdæg. Насколько я поняла, здесь же не этимология, а просто параллели для образования этих штук. Пока не делала циты и не переводила на английский.
![image](https://user-images.githubusercontent.com/13102259/67140691-bc859300-f265-11e9-8e29-34bd7fee7535.png)
И еще я не нашла ни в каких списках Ahlquist...

**Comment by solanum-tuberosum** [comment]
Слово kærī, тоже пока не делала циты и не переводила на англ.
![image](https://user-images.githubusercontent.com/13102259/67317869-63db2200-f513-11e9-87e5-6fdf3ce1f498.png)

**Comment by solanum-tuberosum** [comment]
Вот здесь тоже. Во втором случае не стала делать cit.
![image](https://user-images.githubusercontent.com/13102259/67469669-31394280-f655-11e9-8d77-54516e3ab54f.png)

PS еще я нашла в википедии слово свербига, а не свербега. Надо исправить?

**Comment by solanum-tuberosum** [comment]
И вот здесь... Мб потому что здесь не этимология, а просто пример на семантику?.. Пока тоже не делала циты и не переводила
![image](https://user-images.githubusercontent.com/13102259/67478834-854c2300-f665-11e9-989a-0187ba7cd53e.png)

**Comment by solanum-tuberosum** [comment]
А может быть в cit'е сделать возможность помечать что он сомнительный? и чтобы он делался нежирным соответственно?
и помечать, например, что это просто семантическая параллель...
тогда мы смогли бы автоматически получить списки с нормальной этимологией, с чем-то сомнительным и с семантическими параллелями

**Comment by solanum-tuberosum** [comment]
Вот еще, здесь пока сделала циты
![image](https://user-images.githubusercontent.com/13102259/67852435-6f36da80-fb1d-11e9-9d87-31e894a0dad3.png)

**Comment by obelyaev** [comment]
Я не думаю, что есть систематическая корреляция с сомнительностью. Скорее это ошибки при наборе. Нормальный указатель в любом случае должен включать ссылки на все упоминания того или иного языка или формы, а не только на "надёжные" (потому что само-то упоминание надёжно, это вот рассуждение может хромать; но я точно знаю, что у Абаева есть сомнительные рассуждения, где всё-таки язык жирным). Я бы не стал так глубоко копать.
