### ISSUE TITLE
Форматирование: subentry сразу после леммы

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#86]
![image](https://user-images.githubusercontent.com/13102259/66925637-603c2c80-f035-11e9-94a2-3e427f6e65b4.png)
должно ставиться двоеточие перед сабентри
если ставить к сабэнтри прекоммент с типом "colon", то перед ним ставится пробел
![image](https://user-images.githubusercontent.com/13102259/66925843-b610d480-f035-11e9-9233-a77c6ecd5227.png)
Забить вообще на двоеточие и убрать прекоммент? Или что?

**Comment by solanum-tuberosum** [comment]
Еще раз это встретилось:
![image](https://user-images.githubusercontent.com/13102259/67752188-97eaa180-fa43-11e9-99d1-ac2d6495808e.png)

Здесь прокатило с прекомментом, потому что не был указан дигорский/иронский
![image](https://user-images.githubusercontent.com/13102259/67752214-ac2e9e80-fa43-11e9-89ef-c73bfc90ea42.png)

**Comment by obelyaev** [comment]
Это двоеточие вообще должно было ставиться автоматически, и скрипт для этого был. Никакого PreComment не надо. Но в скрипте была небольшая ошибка. Теперь этой ошибки нет.

**Comment by solanum-tuberosum** [comment]
Два раза встретилась другая ситуация: сабэнтри после леммы с прекомментом, но при этом двоеточие не ставится.
Забить?
![image](https://user-images.githubusercontent.com/13102259/75346843-9d9caa80-58b0-11ea-9973-899ad0ba4680.png)
