### ISSUE TITLE
ужасные кабардинцы (жирные cit'ы без form и прочее)

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#87]
Слишком много проблем со словом kæsæg.
![image](https://user-images.githubusercontent.com/13102259/67750837-0aa64d80-fa41-11e9-892d-53b6fdf35e03.png)
![image](https://user-images.githubusercontent.com/13102259/67750858-142fb580-fa41-11e9-887a-b8488adc41f8.png)
1. Что делать с жирными как бы cit'ами, у которых нет form?
2. Повесть временных лет. Сделать возможность убирать не только автора, но и сам источник?))) + Нет еще трех выделенных источников  #46 
3. Жирные сваны отделены от их слова, надо тут тоже сделать hide language. #55 
(ну и перевод этого всего очень сомнительный получился)

**Comment by obelyaev** [comment]
1. По нынешней системе, видимо, просто их писать жирным. С другой стороны, для указателя языков было бы полезно это учитывать. М.б. пустые циты без форм?

2. ПВЛ — вот уж не знаю. Хотелось бы отметить это как источник. По идее надо бы в скобках заменить текст на нормальную библиографическую ссылку ("изд. 1950 г." — это не нормально). Собственно, вот: Повесть временных лет. — М.—Л.: Изд-во Акад. наук СССР, 1950.  Это можно в Text, скорее всего (вряд ли где-то ещё втсречается).

3. Хайдлэнгвидж уже сделалъ.
