### ISSUE TITLE
формы без указания языка

### ISSUE THREAD

**Issue by obelyaev** [obelyaev/abaevdict#90]
Надо решить, что делать в случаях, когда в статье цитируются слова, которые можно привязать к какому-то языку без контекста, но при которых язык не указан. Пример — слово æncajyn. В нём цитируется довольно много праиранских форм, которые, как кажется, могут быть важными для поиска и составления указателя. Пока что они даны просто как слова курсивом. Правильно ли это? Я вижу два способа это учитывать:

1. Вставлять как \<cit\> без указания языка. Этот способ имеет мало смысла: разве что такие слова можно будет найти, если искать по всем формам, но обычно даже при таком поиске нужно знать, из какого языка взято слово.

2. Указывать язык, но скрывать его каким-то образом. Можно, например, предусмотреть флажок "Hide language".

Что думаете?

(я сейчас активно работаю над словарём, извините за задержку; в ближайшие дни должен открыть базу)

**Comment by jvsntsn** [comment]
Мы с Ирой за второй вариант однозначно. 

P.S Вы тоже нас извините, что так поздно отвечаем

**Comment by obelyaev** [comment]
Спасибо! Да, мне тоже так кажется. Флажок Hide добавить несложно. Базу я в ближайшее время доделаю, и надо будет собраться. Есть некоторые новости. Из хорошего — я начал вычитывать лексемы (из Юлиной части). Это занимает довольно много времени, но при этом качество перевода и передачи иноязычных слов в целом неплохое.

**Comment by jvsntsn** [comment]
Ура, я очень рада!
Насчет собраться -- можно ли успеть это сделать до 24 февраля? Потом я уезжаю на 10 дней до 4 марта, а пропускать новости не хотелось бы)

**Comment by obelyaev** [comment]
> Ура, я очень рада!
> Насчет собраться -- можно ли успеть это сделать до 24 февраля? Потом я уезжаю на 10 дней до 4 марта, а пропускать новости не хотелось бы)

Да, можно. Давайте тогда я сделаю объявление в Translators и там уже обсудим дату.

**Comment by solanum-tuberosum** [comment]
> > Ура, я очень рада!
> > Насчет собраться -- можно ли успеть это сделать до 24 февраля? Потом я уезжаю на 10 дней до 4 марта, а пропускать новости не хотелось бы)
> 
> Да, можно. Давайте тогда я сделаю объявление в Translators и там уже обсудим дату.

Если что, я скорее всего уеду как раз в районе 4 марта, так что точно лучше встретиться до отъезда Юли

**Comment by obelyaev** [comment]
См. #55
