### ISSUE TITLE
xref digor

### ISSUE THREAD

**Issue by happyfruitcake** [obelyaev/abaevdict#92]
![capture_20200225150741](https://user-images.githubusercontent.com/19610788/75246422-c8b7c900-57e0-11ea-8d1d-ab32948b8e66.png)

1. Как тут оформить дигорскую форму которая в этимологии (после ~)?
2. Нужно ли создавать слова в xref, которых нет в словаре (afojnad, afojnadæ)?

**Comment by obelyaev** [comment]
>     1. Как тут оформить дигорскую форму которая в этимологии (после ~)?
Если делаете xref, то xref на afojnad и далее простым текстом "| afojnadæ". Кажется, по-другому не получится.

>     2. Нужно ли создавать слова в xref, которых нет в словаре (afojnad, afojnadæ)?
Я думаю, надо создать и поставить там только xref на afojnadyl с поместой SEE.
