### ISSUE TITLE
definition до sense?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#93]
![image](https://user-images.githubusercontent.com/13102259/75333090-8bae0e00-5896-11ea-85a0-e252ba82381c.png)
По идее это не precomment к sense, а definition и sense
Но в тлехе это выглялит вот так:
![image](https://user-images.githubusercontent.com/13102259/75333131-a3859200-5896-11ea-91cb-6910394a730a.png)

**Comment by obelyaev** [comment]
Да, потому что я не предполагал, что такое бывает. Но если дефиниция и сенс всегда в таком порядке, это легко решается простым изменением форматирования. Сейчас попробую это сделать.

**Comment by obelyaev** [comment]
Я сейчас подумал и пришёл к выводу, что всё-таки это PreComment, т.е. имеется в виду, что это трава кишнец, употребляемая в приправу. Но всё равно поменял порядок элементов. А вот запятую после Definition пока делать не стал: для этого нужно писать скрипт, который будет смотреть, какой элемент следует за ним.

**Comment by solanum-tuberosum** [comment]
Т.е. надо изменить и написать это в прекоммент и убрать из definition?

**Comment by obelyaev** [comment]
Да, я так думаю.
