### ISSUE TITLE
уточнение: все что в скобках после примера это сорс?

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#94]
Понимаю, что было ишью (#71 ), но хотела уточнить
![image](https://user-images.githubusercontent.com/13102259/75333796-d67c5580-5897-11ea-812b-21a9a77633c4.png)
Вот здесь "из дигорского фольклора" пихать просто в текстовое поле в сорс, да?

**Comment by solanum-tuberosum** [comment]
А вот это например совсем не похоже на сорс, но посткомменты вроде все еще не в этом месте ставятся
![image](https://user-images.githubusercontent.com/13102259/75339326-55c25700-58a1-11ea-80e3-a48d7d1273d8.png)

**Comment by solanum-tuberosum** [comment]
И вот это тоже такой длинный сорс?
![image](https://user-images.githubusercontent.com/13102259/76506606-7fac7980-645c-11ea-9404-618c6a096520.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/76740491-0627ca80-677f-11ea-885a-c41619a3d02c.png)
ну это точно не сорс...

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/76839319-5d44a280-6846-11ea-9c9b-1d90e39ea404.png)
продолжаю пополнять коллекцию "сорсов"

**Comment by obelyaev** [comment]
Первое — сорс, остальное — не сорс.

**Comment by obelyaev** [comment]
По логике это всё PostComment'ы. Опять же, вопрос такой же, как про посткомменты к формам: умрёт ли кто-то, если мы все их сделаем после перевода? Или всё-таки это часто важное различие?

Если его проводить, то я вижу разные решения, но красивых среди них нет. Например: сделать перевод отдельным элементом со своим текстовым полем, и уже к нему делать PostComment. Это потребует серьёзной модификации всех существующих слов. Наверное, это можно сделать при помощи скрипта, но это будет непросто.

**Comment by solanum-tuberosum** [comment]
Вообще это все выглядит как такое текстовое поле, в которое при желании можно вставлять сорс. Т.е. можно не менять наши посткомменты, а добавить новый элемент (не знаю, насколько это разумно)
Т.е. там всегда что-то пишется в скобках обычным текстом, но можно и добавить сорс.
Т.е. в случае #105 это можно было бы так сделать. сначала написать вопросик, а потом просто добавить в это поле сорс

**Comment by solanum-tuberosum** [comment]
И кстати это решит проблему двух сорсов #88 (последнее сообщение в ветке)
(но не решит проблему двух переводов...)

**Comment by obelyaev** [comment]
Да, мысль понятна, но опять же придётся менять структуру файла. Сейчас-то просто есть элемент Source внутри примера. А его надо будет во что-то вложить.

**Comment by solanum-tuberosum** [comment]
Снова два сорса! С этим все-таки надо что-то сделать...
![image](https://user-images.githubusercontent.com/13102259/77223349-c4c36080-6b6c-11ea-8a81-e08e6fc5920b.png)

Можно завести особое текстовое поле SourceTXT)) которое по умолчанию показывается в скобках. и мочь вкладывать в него Source и обычный текст, например

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/77433293-44149680-6df0-11ea-92ae-18f1668e7acb.png)

**Comment by solanum-tuberosum** [comment]
Ужасно!! при этом еще можно заметить, что посткоммент между примером и переводом тоже нужен! я вот туда записала дигорскую форму. Но отдельное поле TextSource тоже очень нужно, очень много таких примеров((
![image](https://user-images.githubusercontent.com/13102259/77627725-5c9fc080-6f58-11ea-8a88-3002cd034439.png)

**Comment by solanum-tuberosum** [comment]
У меня это в каждом третьем слове, это ужасно))
![image](https://user-images.githubusercontent.com/13102259/77632506-2580dd80-6f5f-11ea-8b3d-5fc927e637d5.png)

**Comment by solanum-tuberosum** [comment]
Слово ḱʼīrī
![image](https://user-images.githubusercontent.com/13102259/77728996-bb277600-700e-11ea-995c-324b58dc481a.png)

**Comment by solanum-tuberosum** [comment]
> Ужасно!! при этом еще можно заметить, что посткоммент между примером и переводом тоже нужен! я вот туда записала дигорскую форму. Но отдельное поле TextSource тоже очень нужно, очень много таких примеров((
> ![image](https://user-images.githubusercontent.com/13102259/77627725-5c9fc080-6f58-11ea-8a88-3002cd034439.png)

А вот здесь кстати аналогичная дигорская форма просто дана в качестве другого примера
![image](https://user-images.githubusercontent.com/13102259/77735456-a4d3e700-701b-11ea-8db8-07a6c6541d94.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/77742546-b15e3c80-7027-11ea-9c84-990ba3d0799a.png)

**Comment by solanum-tuberosum** [comment]
Кстати здесь https://github.com/abaevdict/abaevdict/issues/81 и здесь https://github.com/abaevdict/abaevdict/issues/98 та же самая проблема по идее

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/77820979-79bec580-70f7-11ea-8868-ed219d3c0310.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/77821034-e89c1e80-70f7-11ea-9dec-86c4bb906faf.png)

**Comment by solanum-tuberosum** [comment]
Слово kʼūl
![image](https://user-images.githubusercontent.com/13102259/77844585-7afff900-71b0-11ea-893d-1eb588af83bd.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/78220367-10113380-74ca-11ea-95ff-eb1468f3f3b4.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/78333756-1d462500-7593-11ea-8be9-e615f9d8630d.png)

**Comment by solanum-tuberosum** [comment]
Тут миллион сообщений, поэтому краткое содержание:

1. в слове ḱīnyg - сорс, так и сделала

2. в словах koj, k˳yris, kʼabaz, kʼaj, kʼæm - посткоммент, пока они лежат в сорсе, ждут пока мы разберемся с посткомментами
+ надо не забыть про пример на другой тип посткоммента https://github.com/abaevdict/abaevdict/issues/94#issuecomment-604871084_

3. в словах ḱʼīrī, kʼæssa, kʼona, kʼuma, kʼul, kʼ˳ydīly, kʼ˳ylyx - сделала прекоммент к сорсу (по смыслу немного не так, но хотя бы показывается нормально). если плохо, то потом можно переделать

4. в словах kʼælwa, kʼæsær, kʼūxylxæcæg все плохо, из-за того что там два сорса. 
Привожу еще раз их скриншоты
![image](https://user-images.githubusercontent.com/13102259/78421103-e6891100-765d-11ea-83e1-09a6d2f2e912.png)
![image](https://user-images.githubusercontent.com/13102259/78421123-00c2ef00-765e-11ea-9a24-807f3e36a136.png)
![image](https://user-images.githubusercontent.com/13102259/78421124-03bddf80-765e-11ea-88dd-f856df60bcf7.png)
эта проблема дублирует проблему возможности вставлять сорсы в этимологию(=текстовое поле, см. https://github.com/abaevdict/abaevdict/issues/124 и https://github.com/abaevdict/abaevdict/issues/118). если ее решить, то можно будет добавлять это в прекоммент к сорсу.

Не решит проблему третьего слова, потому что там по сути посткоммент к сорсу, проблема посткоммента к сорсу обсуждалась в https://github.com/abaevdict/abaevdict/issues/81 и https://github.com/abaevdict/abaevdict/issues/98, но его пока все еще нет)

**Comment by solanum-tuberosum** [comment]
UPD осознала, что к примерам можно добавлять два сорса, но форматирование получается не совсем такое, как надо
![image](https://user-images.githubusercontent.com/13102259/78470396-e4908200-7731-11ea-975d-354ec5aa8a2e.png)
___
![image](https://user-images.githubusercontent.com/13102259/78470444-536ddb00-7732-11ea-9f47-0595c1490ff6.png)
___
![image](https://user-images.githubusercontent.com/13102259/78470496-b8c1cc00-7732-11ea-8695-b1eeda93bf19.png)

**Comment by solanum-tuberosum** [comment]
:(
Слово kʼ˳yrī
![image](https://user-images.githubusercontent.com/13102259/78471034-b5c8da80-7736-11ea-8092-e27465cc45d8.png)

**Comment by obelyaev** [comment]
Так, смотрите, я вроде пофиксил эту проблему. Теперь есть отдельные элементы ExampleText и Translation; к ExampleText может быть свой PostComment. А PostComment ко всему примеру ставится после перевода, но перед сорсом. Кроме того, я сделал так, что если есть и PostComment, и Source, то они автоматически объединяются под общими скобками и между ними ставится точка с запятой. Правда, в последнем случае у Абаева это не так. Но я предполагаю, что это случайность, потому что я не вижу разницы в употреблении пояснения в скобках между этим примером и другими.
