### ISSUE TITLE
странное постсабэнтри и миллион других вопросов про kūryn

### ISSUE THREAD

**Issue by solanum-tuberosum** [obelyaev/abaevdict#97]
![image](https://user-images.githubusercontent.com/13102259/76162466-22a87f00-614f-11ea-990e-8412d02415a8.png)
* Насколько я поняла, здесь есть пресабэнтри, потом примеры, потом постсабэнтри (начинается с первого выделенного тире), то потом еще есть тире! и после тире еще видимо постсабэнтри (я так сделала). а потом уже снова примеры. но перед ними нет тире... я запуталась в общем.

* И в переводе я не особо понимаю, что значит "выйти на тревогу"

* В этимологии ссылка на guppur
![image](https://user-images.githubusercontent.com/13102259/76162498-6bf8ce80-614f-11ea-87a7-5a369009f340.png)
Но ближайшее существующее слово g˳yppyrsar, в котором написано следующее: 
![image](https://user-images.githubusercontent.com/13102259/76162522-9ba7d680-614f-11ea-9d13-84670780e8de.png)
я пока поставила там ссылку на g˳yppyr, и в kūryn тоже поставила на него ссылку. но так в целом не очень понятно, правильно ли так делать...

**Comment by obelyaev** [comment]
>     * Насколько я поняла, здесь есть пресабэнтри, потом примеры, потом постсабэнтри (начинается с первого выделенного тире), то потом еще есть тире! и после тире еще видимо постсабэнтри (я так сделала). а потом уже снова примеры. но перед ними нет тире... я запуталась в общем.
Всё правильно, только примеры идут не ко всему слову, а к сабэнтри kurdiad. Поэтому, наверное, и точка с запятой. У нас в этом случае ставится двоеточие, но это норм, мне кажется.
>     * И в переводе я не особо понимаю, что значит "выйти на тревогу"
Я так понимаю, имеется в виду, "право выйти не просто так, а с целью реакции на тревогу". Не знаю, как перевести. "to go out (to react to the alarm)", может быть.
>       я пока поставила там ссылку на g˳yppyr, и в kūryn тоже поставила на него ссылку. но так в целом не очень понятно, правильно ли так делать...
Я думаю, что правильно. Надо завести такой энтри в словаре в любом случае. Если он действительно обсуждается при тымбыл, можно поставить "см. тымбыл". А дигорскую форму в этимологии можно сделать как обычно у Абаева: после вертикальной черты курсивом.
