### ISSUE TITLE
ссылка на слово содержит другую первую букву

### ISSUE THREAD

**Issue by jvsntsn** [obelyaev/abaevdict#99]
![image](https://user-images.githubusercontent.com/48504970/76608576-eb5b1900-6526-11ea-9e89-7fb965a9e94c.png)
вот тут выделенное слово у меня начинается на ḱ такое, а само вхождение к статье по этому слову начинается просто на k...

**Comment by obelyaev** [comment]
Это опечатка во вхождении слова, там должно быть ḱ. В иронском вообще сочетание "ки" фонотактически невозможно.
